USE [master]
GO

/****** Object:  Database [HumanResourcesDB]    Script Date: 15.06.2021 20:50:32 ******/
CREATE DATABASE [HumanResourcesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HumanResourcesDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HumanResourcesDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HumanResourcesDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HumanResourcesDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HumanResourcesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HumanResourcesDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HumanResourcesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HumanResourcesDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HumanResourcesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HumanResourcesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET RECOVERY FULL 
GO

ALTER DATABASE [HumanResourcesDB] SET  MULTI_USER 
GO

ALTER DATABASE [HumanResourcesDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HumanResourcesDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HumanResourcesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HumanResourcesDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HumanResourcesDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HumanResourcesDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HumanResourcesDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HumanResourcesDB] SET  READ_WRITE 
GO

